# Generated by Django 4.1.1 on 2022-09-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
